Build pacman compatible package.

diff --git a/kiss b/kiss
--- a/kiss
+++ b/kiss
@@ -577,6 +577,66 @@ pkg_etcsums() (
     done > "$pkg_dir/$1/$pkg_db/$1/etcsums"
 )
 
+write_kv_pair() {                                                               
+    local key="$1"                                                              
+    shift                                                                       
+                                                                                
+    for val in "$@"; do                                                         
+        if [[ $val = *$'\n'* ]]; then                                           
+            error "$(gettext "Invalid value for %s: %s")" "$key" "$val"            
+            exit $E_PKGBUILD_ERROR                                              
+        fi                                                                      
+        printf "%s = %s\n" "$key" "$val"                                        
+    done                                                                        
+}
+
+write_pkginfo() {
+	source "$1"
+	read -r size _ < <(du -bc | tail -n1)
+
+    #merge_arch_attrs                                                            
+                                                                                
+    printf "# Generated by yonpkg\n"                    
+    #printf "# using %s\n" "$(fakeroot -v)"                                      
+                                                                                
+    write_kv_pair "pkgname" "$pkgname"                                          
+    write_kv_pair "pkgbase" "$pkgbase"                                          
+                                                                                
+	local fullver
+	if (( epoch > 0 )); then
+		fullver="$epoch:$pkgver-$pkgrel"
+	else
+		fullver="$pkgver-$pkgrel"
+	fi
+    write_kv_pair "pkgver" "$fullver"                                           
+                                                                                   
+    # TODO: all fields should have this treatment                               
+    local spd="${pkgdesc//+([[:space:]])/ }"                                       
+    spd=("${spd[@]#[[:space:]]}")                                               
+    spd=("${spd[@]%[[:space:]]}")                                               
+                                                                                
+    write_kv_pair "pkgdesc" "$spd"                                              
+    write_kv_pair "url" "$url"                                                  
+    write_kv_pair "builddate" "$SOURCE_DATE_EPOCH"                              
+    write_kv_pair "packager" "$PACKAGER"                                        
+    write_kv_pair "size" "$size"                                                
+    write_kv_pair "arch" "$pkgarch"                                             
+                                                                                
+    mapfile -t provides < <(find_libprovides)                                   
+    mapfile -t depends < <(find_libdepends)                                     
+                                                                                
+    write_kv_pair "license"     "${license[@]}"                                 
+    write_kv_pair "replaces"    "${replaces[@]}"                                
+    write_kv_pair "group"       "${groups[@]}"                                  
+    write_kv_pair "conflict"    "${conflicts[@]}"                               
+    write_kv_pair "provides"    "${provides[@]}"                                
+    write_kv_pair "backup"      "${backup[@]}"                                  
+    write_kv_pair "depend"      "${depends[@]}"                                 
+    write_kv_pair "optdepend"   "${optdepends[@]//+([[:space:]])/ }"            
+    write_kv_pair "makedepend"  "${makedepends[@]}"                             
+    write_kv_pair "checkdepend" "${checkdepends[@]}"
+}
+
 pkg_tar() (
     # Create a tarball from the built package's files. This tarball also
     # contains the package's database entry.
@@ -588,7 +648,9 @@ pkg_tar() (
     # Use 'cd' to avoid needing tar's '-C' flag which may not be portable
     # across implementations.
     cd "$pkg_dir/$1"
-
+	write_pkginfo "$(pkg_find "$1")/PKGBUILD"	
+	fakeroot -- env LANG=C bsdtar -czf .MTREE --format=mtree --options='!all,use-set,type,uid,gid,mode,time,size,md5,sha256,link' .PKGINFO *
+	
     # Create a tarball from the contents of the built package.
     tar cf - . | case ${KISS_COMPRESS:=gz} in
         bz2)  bzip2 -z ;;
@@ -686,7 +748,9 @@ pkg_build() {
 		srcdir="$mak_dir/$pkg"
 		pkgdir="$pkg_dir/$pkg"
 		prepare
-
+		build
+		package
+		set +e
         # Call the build script, log the output to the terminal and to a file.
         # There's no PIPEFAIL in POSIX shelll so we must resort to tricks like
         # killing the script ourselves.
@@ -720,14 +784,15 @@ pkg_build() {
 
         # Create the manifest file early and make it empty. This ensures that
         # the manifest is added to the manifest.
-        : > "$pkg_dir/$pkg/$pkg_db/$pkg/manifest"
+#        : > "$pkg_dir/$pkg/$pkg_db/$pkg/manifest"
 
         # If the package contains '/etc', add a file called 'etcsums' to the
         # manifest. See comment directly above.
-        [ -d "$pkg_dir/$pkg/etc" ] && : > "$pkg_dir/$pkg/$pkg_db/$pkg/etcsums"
+#        [ -d "$pkg_dir/$pkg/etc" ] && : > "$pkg_dir/$pkg/$pkg_db/$pkg/etcsums"
+	
 
         pkg_strip    "$pkg"
-        pkg_manifest "$pkg"
+#        pkg_manifest "$pkg"
         pkg_fix_deps "$pkg"
         pkg_etcsums  "$pkg"
         pkg_tar      "$pkg"
